### PR TITLE
Update Jameica runtime to 46

### PR DESCRIPTION
**Pull request by yakushabb**
- Update Jameica runtime to 46 since runtime version 44 has reached end-of-life.
- Fix appdata papercuts

### CODE REVIEW

**Comment by yakushabb** [comment]
> "appstream-missing-icon-file"

**Comment by bbhtt** [comment]
The icon supplied is 64px only, it needs a 128px or more.

**Comment by yakushabb** [comment]
> The icon supplied is 64px only, it needs a 128px or more.

@bbhtt  Fixed.

**Comment by tobias-hammerschmidt** [comment]
Thanks for your contribution! I only have 2 questions/remarks wrt this PR:

1. Have you checked whether Jameica already contains a high-res icon which we can directly install instead of putting it here in the repository?
2. I haven't checked in detail but it looks like the changes in the metainfo.xml file will result in a mixture of english and german description?

**Comment by yakushabb** [comment]
The archive file (https://willuhn.de/products/jameica/releases/current/jameica/jameica-linux64-2.10.4.zip) only contains one image (jameica-icon.png) with dimensions of 64px x 64px.

Fixed metainfo issues related to missing lang tags.

**Comment by tobias-hammerschmidt** [comment]
Fine then we'll go with the provided image.

**Pull request merged**
